### ISSUE TITLE
autostartliota script contains wrong liotad.py path

### ISSUE THREAD

**Issue by eifinger** [vmware/liota#211]
As the pip install method isnt supported right now I cloned the repo and executed setup.py install as well as post-install-setup.py.
In the resulting setup the correct path to liotad.py is:
/usr/lib/liota/packages/liotad/liotad.py
This is the current line in the script:
https://github.com/vmware/liota/blob/bbe7efadba4eb1b74f3474bf68039d272e4fbaf5/scripts/autostartliota#L46

**Comment by KohliDev** [comment]
Thanks for pointing this out. We are planning to have a better and alternate restart mechanism (using Liota debian, rpm service) hence we missed updating this file.

In order to have restart functionality you can manually edit autostartliota script with the correct path of Liotad and copy the script in init.d directory.
